#!/bin/bash

# usage example:
# ./um -S "Backup Failed" -b "Check logs" -a file1 -a file2

/usr/bin/umail \
  --server smtp.gmail.com \
  --user alekgoldfinch@gmail.com \
  --to globalalek@gmail.com \
  --cc a.scheglov@arenadata.io \
  --secret /var/tmp/.umail/.umail \
  "$@"
